/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Stitch mockup theme colors
        "tertiary-container": "#390c00",
        "on-error-container": "#93000a",
        "primary": "#000000",
        "on-secondary-fixed": "#231b00",
        "surface-tint": "#5f5e5e",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#1c1b1b",
        "surface-container-high": "#eae8e2",
        "primary-fixed": "#e5e2e1",
        "on-tertiary-fixed": "#390c00",
        "on-background": "#1b1c18",
        "inverse-surface": "#30312d",
        "error": "#ba1a1a",
        "surface-container-low": "#f5f3ed",
        "outline": "#747878",
        "on-primary-container": "#858383",
        "on-surface": "#1b1c18",
        "secondary": "#725c00",
        "on-error": "#ffffff",
        "surface": "#fbf9f3",
        "error-container": "#ffdad6",
        "background": "#fbf9f3",
        "tertiary": "#000000",
        "inverse-primary": "#c9c6c5",
        "secondary-container": "#fed74c",
        "on-secondary": "#ffffff",
        "surface-container": "#f0eee8",
        "tertiary-fixed": "#ffdbd0",
        "on-tertiary-container": "#e25621",
        "surface-container-highest": "#e4e2dd",
        "on-secondary-container": "#735d00",
        "surface-bright": "#fbf9f3",
        "secondary-fixed": "#ffe07e",
        "secondary-fixed-dim": "#e9c339",
        "primary-container": "#1c1b1b",
        "on-tertiary-fixed-variant": "#832600",
        "surface-dim": "#dcdad4",
        "on-surface-variant": "#444748",
        "inverse-on-surface": "#f3f1eb",
        "outline-variant": "#c4c7c7",
        "primary-fixed-dim": "#c9c6c5",
        "on-primary-fixed-variant": "#474646",
        "surface-variant": "#e4e2dd",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#564500",
        "tertiary-fixed-dim": "#ffb59d",

        // Lumora Pay specific color guidelines from Section 5
        stellarBlack: "#080808",
        warmWhite: "#F7F5EF",
        signalYellow: "#FFD84D",
        stellarOrange: "#FF6B35",
        softCream: "#EEEAE0",
        graphite: "#242424",
        mutedGray: "#737373",
        borderGray: "#D8D4CA",
        success: "#168A5B",
        warning: "#B96B00",
        info: "#315EFB"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "lg": "40px",
        "xl": "64px",
        "xs": "8px",
        "md": "24px",
        "base": "4px",
        "gutter": "24px",
        "sm": "16px",
        "container-max": "1280px"
      },
      fontFamily: {
        "mono-data": ["Courier Prime", "monospace"],
        "mono-amount": ["Courier Prime", "monospace"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "mono-data": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "mono-amount": ["20px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "display-lg-mobile": ["40px", { "lineHeight": "1.1", "letterSpacing": "0", "fontWeight": "700" }],
        "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "0", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "0", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-sm": ["14px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
